apiVersion: v1
kind: Service
metadata:
  name: astro-service
  namespace: astro-mc-internal
spec:
  type: NodePort
  selector:
    app: astro-pod
  ports:
  - port: 80
    targetPort: astro-port
    protocol: TCP
